SVM

In [1]:
import pandas as pd
from sklearn import svm, metrics
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [2]:
swell_hrv = pd.read_csv('data/2. final/datasets/hrv/swell/combined/classification\combined-swell-classification-hrv-dataset.csv')

In [3]:
swell_hrv.columns

Index(['MEAN_RR', 'MEDIAN_RR', 'SDRR', 'RMSSD', 'SDSD', 'SDRR_RMSSD', 'HR',
       'pNN25', 'pNN50', 'SD1', 'SD2', 'KURT', 'SKEW', 'MEAN_REL_RR',
       'MEDIAN_REL_RR', 'SDRR_REL_RR', 'RMSSD_REL_RR', 'SDSD_REL_RR',
       'SDRR_RMSSD_REL_RR', 'KURT_REL_RR', 'SKEW_REL_RR', 'VLF', 'VLF_PCT',
       'LF', 'LF_PCT', 'LF_NU', 'HF', 'HF_PCT', 'HF_NU', 'TP', 'LF_HF',
       'HF_LF', 'sampen', 'higuci', 'condition', 'subject_id', 'MEAN_RR_LOG',
       'MEAN_RR_SQRT', 'TP_SQRT', 'MEDIAN_REL_RR_LOG', 'RMSSD_REL_RR_LOG',
       'SDSD_REL_RR_LOG', 'VLF_LOG', 'LF_LOG', 'HF_LOG', 'TP_LOG', 'LF_HF_LOG',
       'RMSSD_LOG', 'SDRR_RMSSD_LOG', 'pNN25_LOG', 'pNN50_LOG', 'SD1_LOG',
       'KURT_YEO_JONSON', 'SKEW_YEO_JONSON', 'MEAN_REL_RR_YEO_JONSON',
       'SKEW_REL_RR_YEO_JONSON', 'LF_BOXCOX', 'HF_BOXCOX', 'SD1_BOXCOX',
       'KURT_SQUARE', 'HR_SQRT', 'MEAN_RR_MEAN_MEAN_REL_RR', 'SD2_LF', 'HR_LF',
       'HR_HF', 'HF_VLF', 'NasaTLX class', 'Condition Label', 'NasaTLX Label'],
      dtype='object')

In [4]:
original_colum_list = ['MEAN_RR', 'MEDIAN_RR', 'SDRR', 'RMSSD', 'SDSD', 'SDRR_RMSSD', 'HR',
       'pNN25', 'pNN50', 'SD1', 'SD2', 'KURT', 'SKEW', 'MEAN_REL_RR',
       'MEDIAN_REL_RR', 'SDRR_REL_RR', 'RMSSD_REL_RR', 'SDSD_REL_RR',
       'SDRR_RMSSD_REL_RR', 'KURT_REL_RR', 'SKEW_REL_RR', 'VLF', 'VLF_PCT',
       'LF', 'LF_PCT', 'LF_NU', 'HF', 'HF_PCT', 'HF_NU', 'TP', 'LF_HF',
       'HF_LF', 'sampen', 'higuci', 'condition', 'subject_id', 'MEAN_RR_LOG',
       'MEAN_RR_SQRT', 'TP_SQRT', 'MEDIAN_REL_RR_LOG', 'RMSSD_REL_RR_LOG',
       'SDSD_REL_RR_LOG', 'VLF_LOG', 'LF_LOG', 'HF_LOG', 'TP_LOG', 'LF_HF_LOG',
       'RMSSD_LOG', 'SDRR_RMSSD_LOG', 'pNN25_LOG', 'pNN50_LOG', 'SD1_LOG',
       'KURT_YEO_JONSON', 'SKEW_YEO_JONSON', 'MEAN_REL_RR_YEO_JONSON',
       'SKEW_REL_RR_YEO_JONSON', 'LF_BOXCOX', 'HF_BOXCOX', 'SD1_BOXCOX',
       'KURT_SQUARE', 'HR_SQRT', 'MEAN_RR_MEAN_MEAN_REL_RR', 'SD2_LF', 'HR_LF',
       'HR_HF', 'HF_VLF', 'NasaTLX class', 'Condition Label', 'NasaTLX Label'] 

In [5]:
selected_colum_list = ['MEAN_RR', 'MEDIAN_RR', 'SDRR', 'RMSSD', 'SDSD', 'SDRR_RMSSD', 'HR',
       'pNN25', 'pNN50', 'SD1', 'SD2', 'KURT', 'SKEW', 'MEAN_REL_RR',
       'MEDIAN_REL_RR'] 

In [6]:
stress_data = swell_hrv[selected_colum_list]
stress_label = swell_hrv['NasaTLX Label']

In [7]:
train_data, test_data, train_label, test_label = train_test_split(stress_data, stress_label)

In [8]:
train_data, test_data, train_label, test_label = train_data.iloc[:10000],test_data.iloc[:10000],train_label.iloc[:10000],test_label.iloc[:10000] # 데이터는 10000개로 짤라서 수행

기본 모델

In [9]:
m1 = svm.SVC()
m1.fit(train_data, train_label)
y_pred_m1 = m1.predict(test_data)

C:\Users\leeseungyeup\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [10]:
acc_score = metrics.accuracy_score(test_label, y_pred_m1)
print("acc_score : ", acc_score )
print("confusion_matrix : ")
confusion_matrix(test_label,y_pred_m1)

acc_score :  0.9371
confusion_matrix : 


array([[3035,  267,    7],
       [  12, 3373,   23],
       [  20,  300, 2963]], dtype=int64)

LinearSVC

In [11]:
# LinearSVC
C=1
m2 = svm.LinearSVC(C=C, max_iter=10000)
m2.fit(train_data, train_label)
y_pred_m2=m2.predict(test_data)

acc_score = metrics.accuracy_score(test_label, y_pred_m2)
print("acc_score : ", acc_score )
print("confusion_matrix : ")
confusion_matrix(test_label,y_pred_m2)

acc_score :  0.3518
confusion_matrix : 


C:\Users\leeseungyeup\Anaconda3\lib\site-packages\sklearn\svm\base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


array([[3309,    0,    0],
       [3348,   46,   14],
       [3120,    0,  163]], dtype=int64)

radal basis function

In [12]:
# radal basis function
m3 = svm.SVC(kernel='rbf', gamma=0.7, C=C, max_iter=10000) # gamma는 scale parameter
m3.fit(train_data, train_label)
y_pred_m3=m3.predict(test_data)

acc_score = metrics.accuracy_score(test_label, y_pred_m3)
print("acc_score : ", acc_score )
print("confusion_matrix : ")
confusion_matrix(test_label,y_pred_m3)

C:\Users\leeseungyeup\Anaconda3\lib\site-packages\sklearn\svm\base.py:244: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


acc_score :  0.8247
confusion_matrix : 


array([[2464,  845,    0],
       [   0, 3407,    1],
       [   0,  907, 2376]], dtype=int64)

polynomial kernel

In [ ]:
# polynomial kernel
m4 = svm.SVC(kernel='poly', degree=3, C=C, gamma='auto')
m4.fit(train_data, train_label)
y_pred_m4=m4.predict(test_data)

acc_score = metrics.accuracy_score(test_label, y_pred_m4)
print("acc_score : ", acc_score )
print("confusion_matrix : ")
confusion_matrix(test_label,y_pred_m4)

시각적 표현 사용

In [ ]:
# 시각적 비교를 위한 함수정의 부분
def make_meshgrid(x, y, h=0.2):
    x_min, x_max = x.min() -1, x.max() +1
    y_min, y_max = y.min() -1, y.max() +1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                         np.arange(y_min, y_max, h))
    return xx, yy

def plot_contours(ax, clf, xx, yy, **params):
    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)
    out = ax.contourf(xx, yy, Z, **params)
    return out

In [ ]:
C = 1.0 #regularization parameter
models = (svm.SVC(kernel='linear', C=C),
          svm.LinearSVC(C=C, max_iter=10000),
          svm.SVC(kernel='rbf', gamma=0.7, C=C),
          svm.SVC(kernel='poly', degree=3, gamma='auto', C=C))
models = (clf.fit(train_data,train_label) for clf in models)

In [ ]:
titles = ('SVC with linear kernel',
           'LinearSVC (linear kernel)',
           'SVC with RBF kernel',
           'SVC with polynomial (degree 3) kernel'
           )

In [ ]:
fig, sub = plt.subplots(2, 2)
plt.subplots_adjust(wspace=0.4, hspace=0.4)

x0, x1 = x[:, 0], x[:, 1]
xx, yy = make_meshgrid(x0, x1)

for clf, title, ax in zip(models, titles, sub.flatten()):
    plot_contours(ax, clf, xx, yy,
                 cmap=plt.cm.coolwarm, alpha=0.8)
    ax.scatter(x0, x1, c=y, cmap=plt.cm.coolwarm, s=20, edgecolors='k')
    ax.set_xlim(xx.min(), xx.max())
    ax.set_ylim(yy.min(), yy.max())
    ax.set_xlabel('Sepal lengh')
    ax.set_ylabel('Sepal width')
    ax.set_xticks(())
    ax.set_yticks(())
    ax.set_title(title)
    
plt.show()
    

In [20]:
# model save part
# import pickle
# from sklearn.externals import joblib
# saved_model = pickle.dumps(model)
# joblib.dump(model, 'SVMmodel1.pkl') 
# model_from_pickle = joblib.load('SVMmodel1.pkl')
# predict = model_from_pickle.predict(test_data)
# acc_score = metrics.accuracy_score(test_label, predict)
# print(acc_score)